[build]
    command = "npm run build"
    functions = "functions/"
    publish = "build/"
    environment = { NODE_VERSION = "18.12.1" }
[functions]
    directory = "netlify/functions"
    node_bundler = "esbuild"